### PR TITLE
Enhanced brightness in cover image

### LINKED ISSUE #1: Adjust cover levels?
I don't know what the protocols and policies are around adjusting light values of cover images. It's a shame (IMO!) that so much detail is lost in this one. Here's an adjusted version (_only_ levels, not saturation, etc.) with the result as shown. Is this kind of "improvement" allowed? It would make for a "better" cover, I believe. The [current image is here][1], for quick comparison.

cover-indidents

[1]: https://github.com/standardebooks/linda-brent_incidents-in-the-life-of-a-slave-girl/blob/master/images/cover.jpg

### PR DESCRIPTION
**Pull request by dajare**
Fixes https://github.com/standardebooks/linda-brent_incidents-in-the-life-of-a-slave-girl/issues/1

(Hope I've done this correctly!)

### CODE REVIEW

**Comment by acabal** [comment]
Thanks!

Two things: 

- The new image is almost twice the file size as the old one. Can you save it from source as slightly more compressed? If you're using GIMP then this means reducing the quality when exporting.

- You also have to run `se build-images`  to update the distributed cover in `./src/epub/images/`

**Comment by dajare** [comment]
@acabal - thanks, Alex. Not sure I'm going to manage...

>  •  The new image is almost twice the file size as the old one. Can you save it from source as slightly more compressed? If you're using GIMP then this means reducing the quality when exporting.

This I can do, and ought to have done; I noticed my file size was bigger (although not how much bigger!), and wasn't sure that it was an issue. I'll compress it and save to my fork.

> •  You also have to run `se build-images` to update the distributed cover in ./src/epub/images/

This is where things break down. 😞 I don't have the toolkit installed, and it would be non-trivial for me to install it on the machine I have available at the moment. Either you can pick up the file and do the build-store-update, or ... we just leave it. 😕 

---

**Update** - I've replaced that image with one slightly smaller file-size than the original (the commit is linked, below). I'll leave it up to you if you want to do anything with it! Apologies if my "help" has only added aggro!

**Comment by acabal** [comment]
The cover should go in the `./images/` folder, not in the repo root

**Comment by dajare** [comment]
> The cover should go in the `./images/` folder, not in the repo root

Arrgghhh! I knew that. 🤦  This really isn't going well, is it! 😬 Looks like I uploaded it twice; it is also in its correct location (I believe!).

**Comment by acabal** [comment]
Thanks!

**Comment by dajare** [comment]
Thanks for persevering, @acabal! 👍

**Pull request merged**
